language: node_js
node_js:
- '0.11'
install:
- npm install --verbose --fetch-retries 5
- sudo pip install awscli
- gem install compass
before_script:
- npm run-script bower
script:
- npm run-script travis
env:
  global:
    secure: XtHn8ijC15oQD0RfT+ppsi1n/jVrES0LuBpo7K0nS/1vHO9NajZBoTP8X6mB+Cc2OwvE6tXEJ2YFZZ28GAGQH+NQW9L7IxXvooAvjrtugxFNKsVeU2Llu8UcLmWZ/5YpkwEPTOMN/yBg8vYoa6Pkb0zlK/aKgY6EqgiXu7k098s=
after_success:
  - if [[ "$TRAVIS_BRANCH" != "master" ]]; then echo "Deployments are only done for the master branch. Current branch is $TRAVIS_BRANCH"; exit 0; fi
  - echo "Deploying build $TRAVIS_BUILD_NUMBER"
  - npm run-script deploy
after_failure:
  - "cat /home/travis/build/hamweather/aerisjs/npm-debug.log"